easy = [
    {"country": "Algeria", "capital": "Algiers"},
    {"country": "Argentina", "capital": "Buenos Aires"},
    {"country": "Australia", "capital": "Canberra"},
    {"country": "Belgium", "capital": "Brussels"},
    {"country": "Brazil", "capital": "Brasília"},
    {"country": "Canada", "capital": "Ottawa"},
    {"country": "China", "capital": "Beijing"},
    {"country": "Egypt", "capital": "Cairo"},
    {"country": "France", "capital": "Paris"},
    {"country": "Germany", "capital": "Berlin"},
    {"country": "Greece", "capital": "Athens"},
    {"country": "India", "capital": "New Delhi"},
    {"country": "Indonesia", "capital": "Jakarta"},
    {"country": "Iran", "capital": "Tehran"},
    {"country": "Iraq", "capital": "Baghdad"},
    {"country": "Italy", "capital": "Rome"},
    {"country": "Japan", "capital": "Tokyo"},
    {"country": "Jordan", "capital": "Amman"},
    {"country": "Kenya", "capital": "Nairobi"},
    {"country": "Lebanon", "capital": "Beirut"},
    {"country": "Libya", "capital": "Tripoli"},
    {"country": "Malaysia", "capital": "Kuala Lumpur"},
    {"country": "Mexico", "capital": "Mexico City"},
    {"country": "Morocco", "capital": "Rabat"},
    {"country": "Netherlands", "capital": "Amsterdam"},
    {"country": "New Zealand", "capital": "Wellington"},
    {"country": "Nigeria", "capital": "Abuja"},
    {"country": "Pakistan", "capital": "Islamabad"},
    {"country": "Palestine", "capital": "Jerusalem"},
    {"country": "Poland", "capital": "Warsaw"},
    {"country": "Portugal", "capital": "Lisbon"},
    {"country": "Qatar", "capital": "Doha"},
    {"country": "Russia", "capital": "Moscow"},
    {"country": "Saudi Arabia", "capital": "Riyadh"},
    {"country": "South Africa", "capital": "Pretoria"},
    {"country": "South Korea", "capital": "Seoul"},
    {"country": "Spain", "capital": "Madrid"},
    {"country": "Turkey", "capital": "Ankara"},
    {"country": "United Kingdom", "capital": "London"},
    {"country": "United States", "capital": "Washington, D.C."}
]

medium = [
    {"country": "Afghanistan", "capital": "Kabul"},
    {"country": "Austria", "capital": "Vienna"},
    {"country": "Azerbaijan", "capital": "Baku"},
    {"country": "Bangladesh", "capital": "Dhaka"},
    {"country": "Belarus", "capital": "Minsk"},
    {"country": "Bolivia", "capital": "Sucre"},
    {"country": "Bulgaria", "capital": "Sofia"},
    {"country": "Cambodia", "capital": "Phnom Penh"},
    {"country": "Cameroon", "capital": "Yaoundé"},
    {"country": "Chile", "capital": "Santiago"},
    {"country": "Colombia", "capital": "Bogotá"},
    {"country": "Croatia", "capital": "Zagreb"},
    {"country": "Cuba", "capital": "Havana"},
    {"country": "Czech Republic", "capital": "Prague"},
    {"country": "Denmark", "capital": "Copenhagen"},
    {"country": "Ecuador", "capital": "Quito"},
    {"country": "Ethiopia", "capital": "Addis Ababa"},
    {"country": "Finland", "capital": "Helsinki"},
    {"country": "Ghana", "capital": "Accra"},
    {"country": "Guatemala", "capital": "Guatemala City"},
    {"country": "Hungary", "capital": "Budapest"},
    {"country": "Iceland", "capital": "Reykjavik"},
    {"country": "Ireland", "capital": "Dublin"},
    {"country": "Kazakhstan", "capital": "Astana"},
    {"country": "Kuwait", "capital": "Kuwait City"},
    {"country": "Laos", "capital": "Vientiane"},
    {"country": "Latvia", "capital": "Riga"},
    {"country": "Lithuania", "capital": "Vilnius"},
    {"country": "Myanmar", "capital": "Naypyidaw"},
    {"country": "Nepal", "capital": "Kathmandu"},
    {"country": "Norway", "capital": "Oslo"},
    {"country": "Oman", "capital": "Muscat"},
    {"country": "Panama", "capital": "Panama City"},
    {"country": "Peru", "capital": "Lima"},
    {"country": "Philippines", "capital": "Manila"},
    {"country": "Romania", "capital": "Bucharest"},
    {"country": "Singapore", "capital": "Singapore"},
    {"country": "Sri Lanka", "capital": "Sri Jayawardenepura Kotte"},
    {"country": "Sweden", "capital": "Stockholm"},
    {"country": "Switzerland", "capital": "Bern"},
    {"country": "Thailand", "capital": "Bangkok"},
    {"country": "Tunisia", "capital": "Tunis"},
    {"country": "Ukraine", "capital": "Kyiv"},
    {"country": "Vietnam", "capital": "Hanoi"},
    {"country": "United Arab Emirates", "capital": "Abu Dhabi"}
]

hard = [
    {"country": "Albania", "capital": "Tirana"},
    {"country": "Andorra", "capital": "Andorra la Vella"},
    {"country": "Angola", "capital": "Luanda"},
    {"country": "Armenia", "capital": "Yerevan"},
    {"country": "Bahamas", "capital": "Nassau"},
    {"country": "Bahrain", "capital": "Manama"},
    {"country": "Barbados", "capital": "Bridgetown"},
    {"country": "Belize", "capital": "Belmopan"},
    {"country": "Benin", "capital": "Porto-Novo"},
    {"country": "Bhutan", "capital": "Thimphu"},
    {"country": "Bosnia and Herzegovina", "capital": "Sarajevo"},
    {"country": "Botswana", "capital": "Gaborone"},
    {"country": "Brunei", "capital": "Bandar Seri Begawan"},
    {"country": "Burkina Faso", "capital": "Ouagadougou"},
    {"country": "Burundi", "capital": "Gitega"},
    {"country": "Cape Verde", "capital": "Praia"},
    {"country": "Central African Republic", "capital": "Bangui"},
    {"country": "Chad", "capital": "N'Djamena"},
    {"country": "Comoros", "capital": "Moroni"},
    {"country": "Congo", "capital": "Brazzaville"},
    {"country": "Costa Rica", "capital": "San José"},
    {"country": "Cyprus", "capital": "Nicosia"},
    {"country": "Djibouti", "capital": "Djibouti"},
    {"country": "Dominica", "capital": "Roseau"},
    {"country": "Dominican Republic", "capital": "Santo Domingo"},
    {"country": "El Salvador", "capital": "San Salvador"},
    {"country": "Equatorial Guinea", "capital": "Malabo"},
    {"country": "Eritrea", "capital": "Asmara"},
    {"country": "Estonia", "capital": "Tallinn"},
    {"country": "Eswatini", "capital": "Mbabane"},
    {"country": "Fiji", "capital": "Suva"},
    {"country": "Gabon", "capital": "Libreville"},
    {"country": "Gambia", "capital": "Banjul"},
    {"country": "Georgia", "capital": "Tbilisi"},
    {"country": "Guinea", "capital": "Conakry"},
    {"country": "Guinea-Bissau", "capital": "Bissau"},
    {"country": "Guyana", "capital": "Georgetown"},
    {"country": "Haiti", "capital": "Port-au-Prince"},
    {"country": "Honduras", "capital": "Tegucigalpa"},
    {"country": "Jamaica", "capital": "Kingston"},
    {"country": "Kyrgyzstan", "capital": "Bishkek"},
    {"country": "Lesotho", "capital": "Maseru"},
    {"country": "Liberia", "capital": "Monrovia"},
    {"country": "Luxembourg", "capital": "Luxembourg"}
    {"country": "Antigua and Barbuda", "capital": "Saint John's"},
    {"country": "Grenada", "capital": "Saint George's"}
]

very_hard = [
    {"country": "Kiribati", "capital": "South Tarawa"},
    {"country": "Liechtenstein", "capital": "Vaduz"},
    {"country": "Madagascar", "capital": "Antananarivo"},
    {"country": "Malawi", "capital": "Lilongwe"},
    {"country": "Maldives", "capital": "Malé"},
    {"country": "Mali", "capital": "Bamako"},
    {"country": "Malta", "capital": "Valletta"},
    {"country": "Marshall Islands", "capital": "Majuro"},
    {"country": "Mauritania", "capital": "Nouakchott"},
    {"country": "Mauritius", "capital": "Port Louis"},
    {"country": "Micronesia", "capital": "Palikir"},
    {"country": "Moldova", "capital": "Chișinău"},
    {"country": "Monaco", "capital": "Monaco"},
    {"country": "Mongolia", "capital": "Ulaanbaatar"},
    {"country": "Montenegro", "capital": "Podgorica"},
    {"country": "Mozambique", "capital": "Maputo"},
    {"country": "Namibia", "capital": "Windhoek"},
    {"country": "Nauru", "capital": "Yaren"},
    {"country": "Nicaragua", "capital": "Managua"},
    {"country": "Niger", "capital": "Niamey"},
    {"country": "North Korea", "capital": "Pyongyang"},
    {"country": "North Macedonia", "capital": "Skopje"},
    {"country": "Palau", "capital": "Ngerulmud"},
    {"country": "Papua New Guinea", "capital": "Port Moresby"},
    {"country": "Paraguay", "capital": "Asunción"},
    {"country": "Rwanda", "capital": "Kigali"},
    {"country": "Senegal", "capital": "Dakar"},
    {"country": "Serbia", "capital": "Belgrade"},
    {"country": "Sudan", "capital": "Khartoum"},
    {"country": "Syria", "capital": "Damascus"},
    {"country": "Uruguay", "capital": "Montevideo"},
    {"country": "Uzbekistan", "capital": "Tashkent"},
    {"country": "Venezuela", "capital": "Caracas"},
    {"country": "Yemen", "capital": "Sana'a"},
    {"country": "Zambia", "capital": "Lusaka"},
    {"country": "Zimbabwe", "capital": "Harare"}
]

